Ajout du suivi Matomo et de l'opt-in
betagouv/itou-pilotage pull request #5
Opened 2021-09-08 16:18 UTC by ikarius

# Quoi ?

Tout est dans le titre

# Pourquoi ?

Demande chantier 2

# Comment ?

Modification des fichiers :         
- `src/index.ejs`
- `src/tableaux-de-bord/criteres/index.ejs`
- `src/tableaux-de-bord/employeurs/index.ejs`
- `src/tableaux-de-bord/metiers/index.ejs`
- `src/tableaux-de-bord/prescripteurs/index.ejs`

- ajout d'une option d'opt-in / opt-out de Matomo dans les paramètres de `tarteaucitron`
- ajout du script de tracking Matomo pour le pilotage de l'inclusion

# Divers

Pas de validation / MEP et utilisation d'une PR au préalable (je ne connais pas bien le setup dev de ce projet, une validation est nécessaire).

2021-09-09 09:21 UTC, kemar requested changes
L'implémentation est bonne mais ça me parait un peu lourdingue en termes de DRY :)

Est-ce que tu as une meilleure idée @hellodeloo ?

2021-09-13 10:11 UTC, hellodeloo commented
@kemar Le DRY des scripts footer ici https://github.com/betagouv/itou-pilotage/commit/47352db32b502a15cccb4e168aba7a0f42007df6 
Bueno ?

2021-09-13 11:47 UTC, kemar commented
> @kemar Le DRY des scripts footer ici [47352db](https://github.com/betagouv/itou-pilotage/commit/47352db32b502a15cccb4e168aba7a0f42007df6)
> Bueno ?

LBuenoTM 👍

2021-09-13 11:48 UTC, kemar approved these changes
LGTM

2021-09-13 13:18 UTC, merged